twothings: help install
	@echo "TWOTHINGS is done"

threethings: help main install
	@echo "threethings done"

main: main.cpp
	g++ -o main main.cpp

help:
	@echo "Targets: main, help, install"
	@echo "that could be printed"
	@echo


install:
	@echo "this would be the commands to install"
	@echo
