# notice that you don't explicitly compile or link
# Three.hxx becuase it's included into Three.h
# which is then included into main.cpp
#
# This violates the normal style but is necessary to make
# templates work

main: main.o
	g++ -o main main.cpp
	
